version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Code:Z
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-vhn!u*-za*#yc9a4h)zq0nv0gffvhhu^u$$&wfe293q&eza7s=0"
      - "DJANGO_DEBUG=True"

  db:
    image: postgres:13
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgresql_data: